server:
  port: 9091
dubbo:
  application:
    name: product-service-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  tracker-list: 192.168.139.130:22122
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
image:
  path: http://192.168.139.130:8888
